### ISSUE TITLE
Unzip Error

### ISSUE THREAD

**Issue by Timong-craft** [lemonhandgrenade/hp-datapack#2]
**Describe the bug**
If I want to unzip the datapack or resource pack there is a winrar error that says 'file damaged' and it works for other files

**To Reproduce**
Steps on how you got to the issue:
1. Go to 'the zip folders of the latest release (broom update)'
2. Do  'try to unzip a folder'
3. See error

**Expected behavior**
I should say file damaged

**Screenshots**
I'm from germany so it would be a german screenshot

**Comment by lemonhandgrenade** [comment]
Hello.

This issue is actually a byproduct of the program [PackSquash](https://comunidadaylas.github.io/PackSquash/)
In efforts to compress the packs as much as possible one of the features causes that issue.
In future this shouldn't happen.

Below are the decompressed files if you want them.


[HP.-.Broom.Update_DP.decompressed.zip](https://github.com/lemonhandgrenade/hp-datapack/files/9188265/HP.-.Broom.Update_DP.decompressed.zip)
[HP.-.Broom.Update_RP.decompressed.zip](https://github.com/lemonhandgrenade/hp-datapack/files/9188266/HP.-.Broom.Update_RP.decompressed.zip)

**Comment by Timong-craft** [comment]
Thank you very much, from the docs and description it looks cool I'll give you feed back if there are more things and can you also make it that you can suggest things here becorse people probably don't want to do that. And thanks

**Comment by Timong-craft** [comment]
And the commands to set you into a house don't work

**Comment by lemonhandgrenade** [comment]
What release version are you using?
